services:
  primeproperty-axum:
    container_name: primeproperty_axum
    image: 355355355/primeproperty-axum
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - axum_network
networks:
  axum_network:
    driver: bridge
